<a href="https://colab.research.google.com/github/eswar554/first_work_progress/blob/main/working_on_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Chessboard Pattern

In [14]:
import numpy as np

def chessboard_pattern(n):
    if n < 2:
        raise ValueError("The size of the chessboard must be >= 2")

    chessboard = np.zeros((n, n), dtype=int)

    chessboard[::2, ::2] = 1
    chessboard[1::2, 1::2] = 1

    return chessboard
n = 8
print(chessboard_pattern(n))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


### 2. Y Pattern


In [12]:
def Y_pattern(n):
    result = np.zeros((n, n), dtype=int)

    for i in range(n // 2):
        result[i, i] = 1
        result[i, n - i - 1] = 1

    for i in range(n // 2, n):
        result[i, n // 2] = 1
    return result
print(Y_pattern(n))

[[1 0 0 0 0 0 1]
 [0 1 0 0 0 1 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]


### 3. T Pattern


In [15]:
def T_pattern(num_rows, num_cols):
    result = np.zeros((num_rows, num_cols), dtype=int)

    result[0, :] = 1

    center_col = num_cols // 2
    result[:, center_col] = 1

    return result
num_rows = 5
num_cols = 7
print(T_pattern(num_rows, num_cols))

[[1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]


### 4. Closed Pattern


In [17]:
def closed_pattern(num_rows, num_cols):
    result = np.zeros((num_rows, num_cols), dtype=int)

    result[0, :] = 1
    result[-1, :] = 1
    result[:, 0] = 1
    result[:, -1] = 1

    return result

num_rows = 5
num_cols = 7
print(closed_pattern(num_rows, num_cols))

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


### 5. Plus Pattern


In [18]:
def plus_pattern(n):
    result = np.zeros((n, n), dtype=int)

    center = n // 2
    result[center, :] = 1

    result[:, center] = 1

    return result

n = 5
print(plus_pattern(n))


[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


### 6. Standardization


In [19]:
import numpy as np

def standardize(array_2D):
    mean = np.mean(array_2D, axis=0)
    std = np.std(array_2D, axis=0)

    standardized_array = (array_2D - mean) / std

    return standardized_array

array_2D = np.array([[1.0, 2.0, 3.0],
                      [4.0, 5.0, 6.0],
                      [7.0, 8.0, 9.0]])
print(standardize(array_2D))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


### 7. Normalisation


In [22]:
def normalise(array_2D):
    mean = np.mean(array_2D, axis=0)
    max_val = np.max(array_2D, axis=0)
    min_val = np.min(array_2D, axis=0)

    normalised_array = (array_2D - mean) / (max_val - min_val)

    return normalised_array

array_2D = np.array([[1.0, 2.0, 3.0],
                      [4.0, 5.0, 6.0],
                      [7.0, 8.0, 9.0]])
print(normalise(array_2D))


[[-0.5 -0.5 -0.5]
 [ 0.   0.   0. ]
 [ 0.5  0.5  0.5]]


### 8. Minkowski Distance between two colored images


In [24]:
def minkowski_distance_between_two_images(image_1, image_2, n):
    grayscale_image_1 = np.mean(image_1, axis=2)
    grayscale_image_2 = np.mean(image_2, axis=2)

    difference = np.abs(grayscale_image_1 - grayscale_image_2)
    minkowski_distance = np.sum(difference**n)**(1/n)

    return minkowski_distance

image_1 = np.random.randint(0, 256, (4, 4, 3))  #image data
image_2 = np.random.randint(0, 256, (4, 4, 3))  # image data
n = 3  # Minkowski distance order
print(minkowski_distance_between_two_images(image_1, image_2, n))

180.76217775710208
